"""固定文案的唯一来源：CLI 生成的一切固定串（分段标签 / 末尾提示 / 按钮 / Title 前缀 / 回执 / 确认闸 / 人读输出 / 校验报错）都从这张表取。

两列 zh / en，key 集合必须完全相同（单测断言）——防止只加了中文忘了英文。
表里的串不含 topic / 路径等运行时值，一律 {占位} 由调用方填；不带参数取值时不做 format，字面的花括号原样保留。

语言由调用方显式传，本模块不读环境变量。解析只在两处发生：ask 入口（JSON lang → AGENT_NTFY_LANG → en）与
daemon / CLI 进程入口（AGENT_NTFY_LANG → en），深层模块只认传进来的 lang。
控制标记（__agent-ntfy:…__）与 Title 里的 [<tag>] 是协议，不在表里、不翻译。
"""

LANGS = ("zh", "en")
DEFAULT_LANG = "en"
ENV_VAR = "AGENT_NTFY_LANG"

TEXTS: dict[str, dict[str, str]] = {
    "zh": {
        # ---- 提问卡片（render）
        "section.doing": "【正在做】",
        "section.background": "【背景】",
        "section.blocker": "【卡点】",
        "section.options": "【选项】",
        "section.reasoning": "【我的建议】",
        "section.question": "【要你定】",
        "option.line": "{i}. **{label}** → {consequence}",
        "option.line_recommended": "{i}. **{label}**（推荐）→ {consequence}",
        "hint": "⚠️ 按钮是快捷选项。\n\n有别的意见请在下方输入框直接回复。\n\n回复发出即生效，不能撤回、也无法追加——请一次说完。",
        # ---- 通知卡（render.render_notify）：没有按钮，末尾只有这一句
        "notify.hint": "想回话，直接在这个 topic 里发消息。",
        # ---- 通知卡输入校验（validate.check_notify）：抬头与正文那条不能沿用提问卡的（那两条写死了 ask 与提问卡的字段名）
        "validate.notify.header": "agent-ntfy notify: 输入校验未通过（{n} 处），全部修正后重试，消息未发送。",
        "validate.notify.hint.body": "通知正文，可用 Markdown（加粗 / 列表 / 分隔线）",
        "validate.notify.body_too_long": "渲染后 {size} 字节，上限 {limit} 字节，超出 {over} 字节。精简 body（不会替你截断）",
        "button.accept": "采纳推荐",
        "reply.head": "【你的回复】",
        "reply.quote_head": "（以下为当时的提问）",
        "reply.truncated": "…（回复过长已截断，agent 已收到全文）",
        # ---- Title 前缀（同 seq 更新时拼在原 Title 前）
        "prefix.answered": "✅ 已回复 · ",
        "prefix.timeout": "⌛ 已超时 · ",
        "prefix.cancelled": "⚠️ 已取消 · ",
        "prefix.released": "✅ 已释放 · ",
        "prefix.not_released": "未释放 · ",
        "prefix.ignored": "已忽略 · ",
        "prefix.superseded": "已被新回执取代 · ",
        "prefix.confirmed": "✅ 已确认 · ",
        # ---- 投递失败回执（inject）
        "receipt.title": "消息未送达",
        "receipt.title_uncertain": "消息可能未送达",
        "receipt.button.release": "释放这个槽位",
        "receipt.button.ignore": "忽略",
        "receipt.not_delivered": "你刚才发的内容没有送达任何 agent。",
        "receipt.uncertain": "无法确认你刚才发的内容有没有送达。",
        "receipt.no_lease": "槽位 {slot} 目前没有绑定任何 agent（没有租约）。",
        "receipt.no_herdr": "这个槽位绑定的目标 {target} 不在 herdr 里（{why}），无法注入。",
        "receipt.no_herdr.bad_output": "pane list 的输出不是预期形态",
        "receipt.pane_missing": "这个槽位绑定的目标 {target} 不在 herdr 的窗格列表里。",
        "receipt.no_pane": "槽位 {slot} 的租约没有登记目标窗格（发起命令的会话不在 herdr 里）。在 herdr 窗格里对这个项目跑任一 agent-ntfy 命令即可登记，或释放这个槽位。",
        "receipt.prompt_timeout": "向目标 {target} 注入时 {why}。",
        "receipt.prompt_failed": "向目标 {target} 注入失败：herdr 返回 {why}。",
        "receipt.wake_failed": "消息已进入目标 {target}（kimi）的队列，但唤醒它失败（herdr 返回 {why}）；它忙着的时候可能不会读到这条，请再发一次。",
        "receipt.error": "注入过程出错（{error}）。",
        "receipt.lease_unreadable": "读取租约失败（状态文件损坏或不可读）。",
        "receipt.stopping": "daemon 正在停止，你刚才的消息未送达，请稍后再发。",
        "receipt.stopping_uncertain": "daemon 正在停止，无法确认你刚才的消息是否送达，请稍后再发。",
        "receipt.superseded": "同一槽位有了新的回执，请看最新那条。",
        "herdr.timeout": "herdr {seconds} 秒无响应",
        "herdr.missing": "herdr 没装或不在 PATH 上",
        "herdr.rc": "退出码 {rc}",
        # ---- 控制按钮的结果
        "control.released": "槽位 {slot} 已释放，可以租给下一个目标。",
        "control.busy_active": "槽位 {slot} 正在使用中（有提问在等回复），未释放。",
        "control.busy_confirming": "槽位 {slot} 正在做可达性确认，未释放。",
        "control.no_lease": "槽位 {slot} 没有租约，无需释放。",
        "control.state_failed": "槽位 {slot} 未释放：状态文件读写失败，看 daemon 日志。",
        "control.ignored": "已忽略，槽位保持原样。",
        # ---- 可达性确认闸的测试消息
        "confirm.title": "确认你能收到通知",
        "confirm.button": "我收到了",
        "confirm.body": ("这是 agent-ntfy 发来的测试消息，用来确认这台手机能收到槽位 {slot} 的通知。\n"
                         "\n"
                         "请在通知栏里点下面的「{button}」按钮——点了就算确认完成，之后 agent 才会往这个槽位发提问。\n"
                         "\n"
                         "如果这条在 ntfy app 里看得见、但通知栏没有弹出来，说明手机的通知权限还没配好："
                         "先按 README 的排查清单逐项检查（通知权限、省电策略、自启动、锁屏通知、这个 topic 没被静音），"
                         "让它弹出来之后再点按钮。只在 app 里点按钮证明不了通知会弹。"),
        # ---- daemon 经 socket 交给 CLI 的文案
        "daemon.bad_request.too_long": "请求超过 {limit} 字节还没见到换行",
        "daemon.bad_request.not_json": "请求不是一行 JSON 对象：{error}",
        "daemon.bad_request.unknown_cmd": "未知命令：{cmd}",
        "daemon.bad_request.release_args": "release 要给 slot 或 leased_by",
        "daemon.bad_request.ask_args": "ask 要给非空 leased_by 与正数 timeout",
        "daemon.bad_request.notify_args": "notify 要给非空 leased_by",
        "daemon.bad_request.confirm_timeout": "confirm-sub 的 timeout 要是正数",
        "daemon.unknown_slot": "没有这个槽位：{slot}（agent-ntfy slots 看现有的）",
        "daemon.no_lease": "这个目标没有租着任何槽位",
        "daemon.release.active": "槽位 {slot} 正有提问等回复，不能释放",
        "daemon.release.confirming": "槽位 {slot} 正在做可达性确认，不能释放",
        "daemon.invalid_input": "输入校验未通过：{problems}",
        "daemon.invalid_input.sep": "；",
        "daemon.bad_request.not_object": "请求不是一行 JSON 对象：顶层不是对象",
        "daemon.busy.pending": "这个目标已有一个提问在 {slot} 上等回复，先等它结束",
        "daemon.busy.confirming": "槽位 {slot} 正在做可达性确认，等它完成后重试",
        "daemon.no_free_slot": "全部槽位已租用。释放一个空闲槽位（agent-ntfy release <slot>，然后重试；候选：{candidates}）或新建（agent-ntfy add-slot，之后要确认）",
        "daemon.no_free_slot.none": "没有可替换的空闲槽位",
        "daemon.no_confirmed_slot": "远程交互模式下只能用已过闸的槽位，而已过闸的都被占用了。释放一个空闲的已过闸槽位（agent-ntfy release <slot>，然后重试；候选：{candidates}），或等用户回到终端给一个空闲槽位过闸（agent-ntfy confirm-sub <slot>）",
        "daemon.candidate.confirmed": "{slot}（已过闸）",
        "daemon.candidate.unconfirmed": "{slot}（未过闸，选它要再动一次手机）",
        "daemon.unconfirmed": "槽位 {slot} 还没确认过手机收得到通知。请用户在自己的终端跑 agent-ntfy confirm-sub {slot}，按提示订阅并点按钮，然后重试",
        "daemon.publish_failed": "向 ntfy 发布失败：{error}",
        "daemon.publish_failed.confirm": "向 ntfy 发布测试消息失败：{error}",
        "daemon.warning.disconnected_at_send": "ntfy 订阅目前断开、仍在重连；提问已发出，回复要等恢复后回放",
        "daemon.warning.disconnected_at_confirm": "ntfy 订阅目前断开、仍在重连；测试消息已发出，点击要等恢复后才收得到",
        "daemon.warning.disconnected": "ntfy 订阅已断开（连续失败 {failures} 次，{seconds} 秒），仍在重连；期间到达的回复要等恢复后回放",
        "daemon.warning.reconnected": "ntfy 订阅已恢复",
        "daemon.warning.text_during_confirm": "收到了文字回复，但只有点按钮才算确认；请在通知栏点「{button}」",
        "daemon.stopping.ask": "daemon 正在停止；提问已发出，用户之后的回复会以指令形式送达",
        "daemon.stopping.confirm": "daemon 正在停止，确认未完成；重启后再跑一次 confirm-sub",
        "daemon.confirm.busy_pending": "槽位 {slot} 正有提问等回复，等它结束再确认",
        "daemon.confirm.busy_confirming": "槽位 {slot} 已在确认中，等它结束再确认",
        "daemon.confirm.mark_failed": "按钮已收到，但订阅状态落盘失败（看 daemon 日志）；修好后再跑一次 confirm-sub",
        # ---- CLI 人读输出
        "cli.start_hint": ("daemon 没在跑。启动方式：\n"
                           "  herdr 内 ：另开一个 pane 跑  agent-ntfy daemon      （可见、herdr 管生命周期）\n"
                           "  非 herdr ：agent-ntfy daemon --detach              （脱离会话，靠 --status / --stop 管）\n"
                           "  ⚠️ 别用 agent 自己内部的 shell 或后台任务起它——agent 一退出它就跟着没了"),
        "cli.connect_failed": "连不上 daemon（{path}：{error}）",
        "cli.connect_failed.not_sent": "连不上 daemon（{path}：{error}）。消息未发送。",
        "cli.no_response": "daemon 没有回应",
        "cli.protocol.not_object": "daemon 回的不是 JSON 对象",
        "cli.bad_env_lang": "AGENT_NTFY_LANG={value} 不是可选值（只认 zh / en）；改成其中之一，或去掉它（缺省 en）",
        "cli.bad_env_ipc": "AGENT_NTFY_IPC={value} 不是可选值（只认 unix / tcp）；改成其中之一，或去掉它（按平台缺省）",
        # ---- argparse 的 help / description（--help 输出）
        "help.prog": "经 ntfy.sh 把需要人拍板的事推到手机，并把裁决带回来",
        "help.home": "状态目录（默认 {home}）",
        "help.ask": "阻塞提问，JSON 从 stdin 读",
        "help.ask.timeout": "等回复的秒数（默认 12 小时）",
        "help.notify": "单向通知（无按钮、不等回复），JSON 从 stdin 读：{\"title\", \"body\"}",
        "help.daemon": "常驻订阅进程",
        "help.daemon.detach": "脱离会话在后台跑",
        "help.daemon.status": "看 daemon 状态",
        "help.daemon.stop": "停掉 daemon",
        "help.slots": "看槽位池与租约",
        "help.release": "释放租约",
        "help.release.slot": "要释放的槽位；不给就释放当前目标租的那个",
        "help.confirm": "可达性确认闸：验该槽位手机收得到通知（在终端跑会显示 topic 名；agent 在 herdr 里代跑会自动开一个窗格让用户在那里做）",
        "help.confirm.slot": "要确认的槽位",
        "help.confirm.again": "已确认过的槽位重新确认（换手机后）",
        "help.confirm.subscribed": "用户已订阅：不显示 topic，直接发测试通知（非终端也能跑）",
        "help.confirm.show_topic": "只打印 topic 名就退出，不发测试通知（会进调用方的输出）",
        "help.confirm.timeout": "等按钮点击的秒数（默认 600）",
        "help.add_slot": "新建一个槽位",
        "help.away": "远程交互模式开关：on 一站式（起 daemon、保证有能用的槽位、再在项目根写 .agent-ntfy/state.json 给 agent 读，不含 topic 名）",
        "help.away.action": "on 开 / off 关 / status 看状态",
        "help.away.json": "status 时打印 state.json 原文（给 agent 读）",
        # ---- away：项目级状态文件
        "cli.away.state.on": "远程交互模式：开",
        "cli.away.state.off": "远程交互模式：关",
        "cli.away.path": "状态文件：{path}",
        "cli.away.slot": "槽位：{slot}（{gate}）",
        "cli.away.slot.none": "槽位：未租用（首次 ask 时自动租）",
        "cli.away.target": "目标身份：{target}",
        "cli.away.updated": "更新于 {updated}",
        "cli.away.not_enabled": "本项目未启用远程交互模式（项目根没有 .agent-ntfy/）；要开：agent-ntfy away on",
        "cli.away.io_failed": "状态文件读写失败：{error}",
        "cli.away.unverified": "daemon 未运行，未校对（以上是状态文件里的记录）",
        "cli.away.corrected": "已按 daemon 的租约校正状态文件",
        "cli.away.unverified.error": "daemon 没能给出租约，未校对（以上是状态文件里的记录）",
        # ---- away on 一站式（daemon 保障 → 槽位保障 → 写状态文件）
        "cli.away.ready": "远程交互模式已开启，槽位 {slot} 就绪",
        "cli.away.ready.lazy": "远程交互模式已开启；槽位首次提问时自动分配（池里有已过闸的空闲槽位）",
        "cli.away.confirm_pane": ("远程交互模式已开启，但槽位 {slot} 还要过一次可达性闸：已在 herdr 窗格 {pane} 里开始确认。请转告用户：\n"
                                  "  1. 看窗格 {pane}，在手机 ntfy app 里订阅它显示的 topic\n"
                                  "  2. 订阅好后在该窗格按回车，会收到一条带按钮的测试通知\n"
                                  "  3. 在手机通知栏点按钮——之后用 agent-ntfy slots 看它过没过闸"),
        "cli.away.confirming": ("远程交互模式已开启；槽位 {slot} 正在确认中（已有一个确认窗格打开）：\n"
                                "  让用户去那个窗格完成订阅并按回车，再在手机通知栏点按钮"),
        "cli.away.daemon_failed": "daemon 没有起来（{seconds} 秒内探不到），远程交互模式未开启；看日志 {log}",
        "cli.away.unwritable": "状态目录 {path} 不可写（已存在但不是目录，或没有写权限）",
        "cli.away.pane_failed": "在 herdr 里开不出窗格（或命令没敲进去），daemon 没有起来，远程交互模式未开启；请在终端跑 agent-ntfy daemon --detach 后重试",
        "cli.slots.pane": "  窗格 {pane}",
        "cli.project.unresolved": "定不出当前项目（{error}）；换到一个存在的目录再跑",
        "cli.reminder": "提醒：{message}",
        "cli.notify.sent": "通知已发到 {slot}（用户想回话会以指令形式送达）",
        "cli.ask.timeout": "{seconds} 秒内没有收到回复（消息已发送，用户之后的回复会以指令形式送达）",
        "cli.ask.error_sent": "消息已发送，但 {message}",
        "cli.ask.error_not_sent": "消息未发送：{message}",
        "cli.ask.candidate": "  可替换：{slot}（{gate}）",
        "cli.ask.candidate.confirmed": "已过闸",
        "cli.ask.candidate.unconfirmed": "未过闸，选它要再动一次手机",
        "cli.ask.disconnected": "daemon 连接中断",
        "cli.ask.disconnected.sent": "（消息已发送，回复无法再送回本次调用）",
        "cli.ask.disconnected.not_sent": "（消息未发送）",
        "cli.ask.comm_failed": "与 daemon 通信失败：{error}",
        "cli.ask.comm_failed.sent": "（消息已发送）",
        "cli.ask.interrupted": "已中断",
        "cli.ask.interrupted.sent": "（消息已发送；用户之后的回复会以指令形式送达）",
        "cli.slots.gate.confirmed": "已过闸",
        "cli.slots.gate.unconfirmed": "未过闸",
        "cli.slots.since": "  {leased_by}  自 {leased_at}",
        "cli.slots.state.unassigned": "未分配",
        "cli.slots.state.idle": "已租用·空闲",
        "cli.slots.state.active": "已租用·活跃",
        "cli.slots.state.confirming": "确认中",
        "cli.released": "已释放 {slot}",
        "cli.confirm.topic": "{slot} 的 topic：{topic}\n订阅地址：{url}",
        "cli.confirm.topic_hint": ("topic 名只在你自己的终端里显示：请在你自己的终端跑  agent-ntfy confirm-sub {slot}\n"
                                   "  用户已经在手机上订阅过就加 --subscribed（不显示 topic，非终端也能跑）；只想看 topic 名用 --show-topic（会进调用方的输出）"),
        "cli.confirm.guide": "在手机 ntfy app 里订阅上面这个 topic；订阅好后按回车，我会发一条带按钮的测试通知——看到它弹出来、点按钮，确认就完成了。",
        "cli.confirm.enter": "订阅好了就按回车…",
        "cli.confirm.already": "{slot} 已经确认过手机收得到通知，不用再做；换了手机要重新确认就加 --again",
        "cli.confirm.protocol": "协议错误：说了 --subscribed 却收到 topic 事件；不打印它。daemon 与 CLI 版本可能不一致",
        "cli.confirm.no_enter": "没等到回车（stdin 已到头），确认取消。请在你自己的终端交互式地跑；用户已订阅过就用 --subscribed",
        "cli.confirm.sent": "测试通知已发出，请在手机通知栏点「{button}」（{seconds} 秒内）…",
        "cli.confirm.done": "✅ {slot} 已确认：手机收得到通知，之后 agent 可以用它提问了",
        "cli.confirm.timeout": "{seconds} 秒内没有收到按钮点击，确认未完成。通知没弹出来？按 README 的排查清单检查后再跑一次",
        "cli.confirm.timeout_no_enter": "{seconds} 秒内没等到回车，确认未完成；测试通知还没发出。订阅好之后再跑一次",
        "cli.confirm.disconnected": "daemon 连接中断，确认未完成",
        "cli.confirm.comm_failed": "与 daemon 通信失败：{error}",
        "cli.confirm.interrupted": "已中断，确认未完成",
        "cli.confirm.pane_opened": ("已在 herdr 窗格 {pane} 里开始 {slot} 的可达性确认。请转告用户：\n"
                                    "  1. 看窗格 {pane}，在手机 ntfy app 里订阅它显示的 topic\n"
                                    "  2. 订阅好后在该窗格按回车，会收到一条带按钮的测试通知\n"
                                    "  3. 在手机通知栏点按钮——之后用 agent-ntfy slots 或 away status 看它过没过闸"),
        "cli.add_slot.done": "已新建 {slot}（还没确认过手机收得到通知）。下一步：在你自己的终端跑  agent-ntfy confirm-sub {slot}",
        "cli.status.not_running": "daemon：未运行",
        "cli.status.no_socket": "daemon：无应答（pid 文件 {pid} 仍在，可能已死）",
        "cli.status.transport": "  传输：{transport}",
        "cli.status.sub.connected": "已连上",
        "cli.status.sub.connecting": "连接中",
        "cli.status.sub.disconnected": "断开 {seconds} 秒",
        "cli.status.line": "daemon：pid {pid}  订阅：{sub}  等待中的提问：{pending}  确认中：{confirming}  槽位：{pool}",
        "cli.stop.no_ack": "daemon（pid {pid}）没有确认停止（{other}）；请手动核实",
        "cli.stop.no_response": "无回应",
        "cli.stop.done": "daemon：pid {pid} 已停",
        "cli.stop.timeout": "daemon pid {pid} 30 秒内没退出",
        "cli.detach.already": "已有 daemon 在跑",
        "cli.detach.died": "daemon 没有起来（退出码 {rc}），看 {log}",
        "cli.detach.started": "daemon：已在后台启动，pid {pid}（日志 {log}）",
        "cli.detach.not_ready": "daemon（pid {pid}）5 秒内还没就绪，仍在启动；稍后用 agent-ntfy daemon --status 看，日志 {log}",
        # ---- 校验报错（validate）
        "validate.header": "agent-ntfy ask: 输入校验未通过（{n} 处），全部修正后重试，消息未发送。",
        "validate.field.body": "正文",
        "validate.hint.title": "通知栏那一行钩子，预览只看得到它",
        "validate.hint.doing": "一句话说这是哪件事",
        "validate.hint.description": "背景展开，写给一个完全没看过执行过程的人",
        "validate.hint.blocker": "具体卡在哪",
        "validate.hint.options": "2~5 个 {id, label, consequence}，consequence 写实际后果",
        "validate.hint.recommend": "推荐项的 id",
        "validate.hint.reasoning": "要写倾向的理由 + 最强的反对意见",
        "validate.hint.question": "一句能被一句话回答的问题",
        "validate.missing": "缺失",
        "validate.not_array": "不是数组（是 {type}）",
        "validate.empty_array": "是空数组",
        "validate.not_string": "不是字符串（是 {type}）",
        "validate.empty_string": "是空串",
        "validate.required": "{why}。必填，{hint}",
        "validate.options.too_few": "只有 {n} 项，要求 {min}~{max} 项（只有一个选项不叫选择）",
        "validate.options.too_many": "有 {n} 项，要求 {min}~{max} 项（多于 {max} 项说明问题没收敛，先想清楚再问）",
        "validate.options.not_object": "第 {i} 项不是对象（是 {type}）。每项要有 id / label / consequence",
        "validate.options.lacking": "第 {i} 项缺 {keys}。每项要有 id / label / consequence，且都非空",
        "validate.options.dup_id": "id 重复：{id}（第 {where} 项）",
        "validate.options.dup_sep": "、",
        "validate.recommend": '"{rec}" 不在 options 的 id 里（现有 id: {ids}）',
        "validate.recommend.none": "无",
        "validate.lang": '"{value}" 不是可选值（只认 {choices}）；固定文案按它切换语言，不给就按 AGENT_NTFY_LANG，再没有就用 en',
        "validate.body_too_long": "渲染后 {size} 字节，上限 {limit} 字节，超出 {over} 字节。精简 description / consequence / reasoning（不会替你截断）",
        "validate.title_too_long": "{size} 字节，上限 {limit} 字节，超出 {over} 字节。title 是通知栏那一行钩子，写短",
        "validate.title_newline": "含换行。title 是通知栏那一行，只能一行",
        "validate.top_not_object": "顶层必须是对象，现在是 {type}",
        "validate.bad_json": "不是合法 JSON：{msg}（第 {line} 行第 {col} 列）",
        # ---- 状态层（state）——会经 daemon 到 CLI 给人看的报错
        "state.none": "无",
        "state.all_leased": "全部槽位已租用，可替换的空闲槽位：{candidates}",
        "state.keychain.bad_name": "钥匙串{label}不合法：{value}（只能用字母、数字、. _ -）",
        "state.keychain.label.service": "服务名",
        "state.keychain.label.account": "账户名",
        "state.keychain.read_failed": "读钥匙串条目 '{service}' 失败（rc={rc}）：{detail}",
        "state.keychain.write_failed": "写钥匙串条目 '{service}' 失败（rc={rc}）：{detail}",
        "state.keychain.not_json": "钥匙串条目 '{service}' 里的内容不是 JSON 数组：{error}",
        "state.keychain.not_str_array": "钥匙串条目 '{service}' 里的内容不是字符串数组",
        "state.keychain.readback_mismatch": "钥匙串条目 '{service}' 写入后回读与写入内容不一致，池子未更新",
        # ---- topic 池存储：文件 / DPAPI 实现的读写、default_store 的选择、security 缺失
        "state.file.corrupt": "topic 池文件 {path} 的内容不是字符串数组（{error}）；确认没被手改过，否则把它移走后重启（会生成新池子，手机要重新订阅）",
        "state.file.read_failed": "读 topic 池文件 {path} 失败：{error}",
        "state.file.write_failed": "写 topic 池文件 {path} 失败：{error}",
        "state.keychain.missing": "找不到 security 命令（钥匙串只在 macOS 上有）；别的平台设 AGENT_NTFY_STORE=file（Linux）或 dpapi（Windows）",
        "state.store.bad_env": "AGENT_NTFY_STORE={value} 不是可选值（只认 {choices}）；不设就按平台缺省：macOS 钥匙串 / Windows DPAPI / 其余 0600 文件",
        "state.dpapi.unavailable": "DPAPI 只在 Windows 上可用（当前平台 {platform}）；别的平台用 AGENT_NTFY_STORE=file 或 keychain",
        "state.dpapi.unprotect_failed": "解密 topic 池文件 {path} 失败（{error}）：它只能由加密它的那个 Windows 用户在同一台机器上解开；换了账户 / 机器就把它移走后重启（会生成新池子，手机要重新订阅）",
        "state.slot.bad_name": "槽位名不合法：{slot}（应形如 slot1）",
        "state.slot.missing": "槽位 {slot} 不存在（池子里只有 {n} 个）",
        "state.active.not_leased": "活跃槽位 {slot} 在租约文件里不是已租用状态，状态不一致，拒绝操作",
        "state.prefix.bad": "topic 前缀不合法：{prefix}（只能用字母、数字、- 和 _，最长 40 位）",
        "state.pool.too_small": "池子至少要有 1 个槽位，给的是 {pool_size}",
        "state.leases.read_failed": "读租约文件 {path} 失败：{error}",
        "state.leases.not_object": "租约文件 {path} 不是 JSON 对象",
        "state.leases.write_failed": "写租约文件 {path} 失败：{error}",
        "state.replace.active": "槽位 {slot} 正有提问等回复，不能替换",
        "state.replace.unassigned": "槽位 {slot} 没有租约，直接 acquire 即可，不需要替换",
        "state.replace.unconfirmed": "槽位 {slot} 未过闸；用户离席时只能用已过闸的槽位",
        "state.touch.unassigned": "槽位 {slot} 没有租约，没有窗格可刷新",
        "state.grant.empty_owner": "leased_by 不能为空（要写清楚谁在用这个槽位）",
        "state.release.active": "槽位 {slot} 正有提问等回复，不能释放",
        "state.release.unassigned": "槽位 {slot} 没有租约，无需释放",
        # ---- ntfy 客户端（ntfyclient）——作为 {error} 进回执 / CLI 文案
        "ntfy.action.empty": "按钮的 label 与 url 都不能为空",
        "ntfy.name.not_string": "{kind}不是字符串（{type}）",
        "ntfy.name.invalid": "{kind}不合法：{why}（长度 {n}）。只能用字母、数字、- 和 _，1~64 位",
        "ntfy.name.kind.topic": "topic",
        "ntfy.name.kind.seq": "sequence ID",
        "ntfy.name.why.empty": "为空",
        "ntfy.name.why.too_long": "超长",
        "ntfy.name.why.whitespace": "含空白字符",
        "ntfy.name.why.illegal": "含非法字符",
        "ntfy.message.empty": "正文不能为空",
        "ntfy.message.too_long": "正文 {n} 字节，超过 {limit} 字节 ntfy 会把它转成附件而不是当消息推送",
        "ntfy.actions.too_many": "按钮 {n} 个，ntfy 最多允许 {limit} 个",
        "ntfy.action.not_object": "按钮不是对象（{type}）",
        "ntfy.action.malformed": "按钮格式不对，至少要有 action 与 label，现有字段：{fields}",
        "ntfy.title.newline": "标题不能含换行",
        "ntfy.echo.topic": "服务端记的 topic 与发出的不一致：{brief}",
        "ntfy.echo.title": "标题回显不一致，发的是 {sent}，服务端记的是 {got}",
        "ntfy.echo.actions": "服务端回显了 {got} 个按钮，发出的是 {sent} 个——JSON 没被当 JSON 解析（发布走错了端点？）：{brief}",
        "ntfy.echo.attachment": "正文被服务端转成了附件而不是消息（正文太长？）：{brief}",
        "ntfy.closed": "订阅已被本进程关闭",
        "ntfy.stream.broken": "订阅流断开：{error}",
        "ntfy.stream.eof": "订阅流被对端关闭（未超时、无异常），需要重连",
        "ntfy.stream.not_utf8": "订阅流里有一行不是 UTF-8（{n} 字节）",
        "ntfy.stream.not_json": "订阅流里有一行不是 JSON（{n} 字节）",
        "ntfy.stream.not_object": "订阅流里有一行不是 JSON 对象（{n} 字节）",
        "ntfy.update.seq_mismatch": "服务端返回的 sequence_id 不是 {seq}，这条没有挂到原消息上：{brief}",
        "ntfy.clear.no_event": "服务端没有返回 message_clear 事件：{brief}",
        "ntfy.clear.seq_mismatch": "清除事件挂在了别的 sequence 上，不是 {seq}：{brief}",
        "ntfy.subscribe.empty": "至少要订阅一个 topic",
        "ntfy.connect.no_socket": "建连后拿不到 socket",
        "ntfy.connect.failed": "连不上 {url}：{error}",
        "ntfy.response.not_json": "服务端返回的不是 JSON：{payload}",
        "ntfy.response.not_object": "服务端返回的不是 JSON 对象：{payload}",
        "ntfy.http": "HTTP {status} {reason}",
        "ntfy.http.detail": "HTTP {status} {reason}：{detail}",
        "ntfy.http.ntfy_code": "{error}（ntfy code {code}）",
        "ntfy.http.rate_limited": "{msg}。这是限流，不是代码错",
        # ---- daemon 起不来（DaemonError）——CLI 打到 stderr
        "daemon_error.bad_lang": "lang 只能是 zh / en，给的是 {value}",
        "daemon_error.socket": "无法监听 IPC：{path}：{error}{hint}",
        "daemon_error.socket.unix_hint": "。unix socket 路径有长度上限（系统上限），换一个短一点的 AGENT_NTFY_HOME",
        "daemon_error.unauthorized": "未认证的连接（token 不符）",
        "daemon_error.bad_ipc": "AGENT_NTFY_IPC 只能是 unix / tcp：{error}",
        "daemon_error.state_init": "状态初始化失败：{error}",
        "daemon_error.already_running": "已有 daemon 在跑（{path} 连得上），不起第二个",
        # ---- --timeout 参数错（argparse）
        "help.timeout.not_number": "不是数字：{text}",
        "help.timeout.not_positive": "要大于 0 秒：{text}",
    },
    "en": {
        "section.doing": "[Doing] ",
        "section.background": "[Background] ",
        "section.blocker": "[Blocker] ",
        "section.options": "[Options]",
        "section.reasoning": "[My recommendation] ",
        "section.question": "[Your call] ",
        "option.line": "{i}. **{label}** → {consequence}",
        "option.line_recommended": "{i}. **{label}** (recommended) → {consequence}",
        "hint": "⚠️ The button is a shortcut.\n\nDisagree? Type your reply in the box below.\n\nA reply takes effect the moment you send it — it can't be withdrawn or amended, so say it all at once.",
        "notify.hint": "To reply, just send a message in this topic.",
        "validate.notify.header": "agent-ntfy notify: input validation failed ({n} issue(s)); fix them all and retry. Message NOT sent.",
        "validate.notify.hint.body": "the notification body; Markdown allowed (bold / lists / rules)",
        "validate.notify.body_too_long": "renders to {size} bytes, limit {limit}, {over} bytes over. Trim body (nothing is truncated for you)",
        "button.accept": "Accept recommended",
        "reply.head": "[Your reply] ",
        "reply.quote_head": "(the question as asked)",
        "reply.truncated": "… (reply too long, truncated here; the agent received the full text)",
        "prefix.answered": "✅ Answered · ",
        "prefix.timeout": "⌛ Timed out · ",
        "prefix.cancelled": "⚠️ Cancelled · ",
        "prefix.released": "✅ Released · ",
        "prefix.not_released": "Not released · ",
        "prefix.ignored": "Ignored · ",
        "prefix.superseded": "Superseded · ",
        "prefix.confirmed": "✅ Confirmed · ",
        "receipt.title": "Message not delivered",
        "receipt.title_uncertain": "Message may not have been delivered",
        "receipt.button.release": "Release slot",
        "receipt.button.ignore": "Ignore",
        "receipt.not_delivered": "What you just sent did not reach any agent.",
        "receipt.uncertain": "Can't tell whether what you just sent was delivered.",
        "receipt.no_lease": "Slot {slot} is not bound to any agent right now (no lease).",
        "receipt.no_herdr": "This slot's target {target} is not inside herdr ({why}); nothing to inject into.",
        "receipt.no_herdr.bad_output": "pane list output is not in the expected shape",
        "receipt.pane_missing": "This slot's target {target} is not in herdr's pane list.",
        "receipt.no_pane": "The lease on slot {slot} has no target pane registered (the session that ran the command was not inside herdr). Run any agent-ntfy command for this project from a herdr pane to register one, or release the slot.",
        "receipt.prompt_timeout": "While injecting into target {target}: {why}.",
        "receipt.prompt_failed": "Injecting into target {target} failed: herdr returned {why}.",
        "receipt.wake_failed": "The message is queued for target {target} (kimi), but waking it failed (herdr returned {why}); while it is busy it may not read this one — please send it again.",
        "receipt.error": "Injection hit an error ({error}).",
        "receipt.lease_unreadable": "Could not read the lease file (state file damaged or unreadable).",
        "receipt.stopping": "The daemon is stopping; your message was not delivered. Please resend later.",
        "receipt.stopping_uncertain": "The daemon is stopping; can't tell whether your message was delivered. Please resend later.",
        "receipt.superseded": "This slot has a newer receipt — see the latest one.",
        "herdr.timeout": "herdr gave no response within {seconds} s",
        "herdr.missing": "herdr is not installed or not on PATH",
        "herdr.rc": "exit code {rc}",
        "control.released": "Slot {slot} released; it can be leased to the next target.",
        "control.busy_active": "Slot {slot} is in use (a question is waiting for a reply); not released.",
        "control.busy_confirming": "Slot {slot} is in the middle of a reachability check; not released.",
        "control.no_lease": "Slot {slot} has no lease; nothing to release.",
        "control.state_failed": "Slot {slot} not released: the state file could not be read/written, see the daemon log.",
        "control.ignored": "Ignored; the slot is left as is.",
        "confirm.title": "Confirm you get notifications",
        "confirm.button": "Got it",
        "confirm.body": ("This is a test message from agent-ntfy to confirm this phone receives notifications for slot {slot}.\n"
                         "\n"
                         "Tap the “{button}” button below in the notification shade — that completes the check, and only then will the agent send questions to this slot.\n"
                         "\n"
                         "If you can see this in the ntfy app but it never popped up in the notification shade, notification permissions are not set up yet: "
                         "go through the README troubleshooting list first (notification permission, battery saver, autostart, lock-screen notifications, this topic not muted), "
                         "get it to pop up, then tap the button. Tapping inside the app does not prove notifications will pop up."),
        "daemon.bad_request.too_long": "request exceeded {limit} bytes without a newline",
        "daemon.bad_request.not_json": "request is not a single-line JSON object: {error}",
        "daemon.bad_request.unknown_cmd": "unknown command: {cmd}",
        "daemon.bad_request.release_args": "release needs slot or leased_by",
        "daemon.bad_request.ask_args": "ask needs a non-empty leased_by and a positive timeout",
        "daemon.bad_request.notify_args": "notify needs a non-empty leased_by",
        "daemon.bad_request.confirm_timeout": "confirm-sub timeout must be positive",
        "daemon.unknown_slot": "no such slot: {slot} (run agent-ntfy slots to list them)",
        "daemon.no_lease": "this target holds no slot",
        "daemon.release.active": "slot {slot} has a question waiting for a reply; can't release it",
        "daemon.release.confirming": "slot {slot} is in the middle of a reachability check; can't release it",
        "daemon.invalid_input": "input validation failed: {problems}",
        "daemon.invalid_input.sep": "; ",
        "daemon.bad_request.not_object": "request is not a single-line JSON object: the top level is not an object",
        "daemon.busy.pending": "this target already has a question waiting on {slot}; wait for it to finish",
        "daemon.busy.confirming": "slot {slot} is in the middle of a reachability check; retry once it finishes",
        "daemon.no_free_slot": "All slots are leased. Release an idle one (agent-ntfy release <slot>, then retry; candidates: {candidates}) or add one (agent-ntfy add-slot, which then needs confirming)",
        "daemon.no_free_slot.none": "no idle slot to take over",
        "daemon.no_confirmed_slot": "In remote mode only confirmed slots can be used, and every confirmed slot is taken. Release an idle confirmed one (agent-ntfy release <slot>, then retry; candidates: {candidates}) or wait for the user to confirm a free slot at their terminal (agent-ntfy confirm-sub <slot>)",
        "daemon.candidate.confirmed": "{slot} (confirmed)",
        "daemon.candidate.unconfirmed": "{slot} (unconfirmed — picking it means one more round on the phone)",
        "daemon.unconfirmed": "Slot {slot} has not been confirmed to reach the phone yet. Ask the user to run agent-ntfy confirm-sub {slot} in their own terminal, subscribe and tap the button as prompted, then retry",
        "daemon.publish_failed": "publishing to ntfy failed: {error}",
        "daemon.publish_failed.confirm": "publishing the test message to ntfy failed: {error}",
        "daemon.warning.disconnected_at_send": "the ntfy subscription is currently down and reconnecting; the question went out, the reply will be replayed once it recovers",
        "daemon.warning.disconnected_at_confirm": "the ntfy subscription is currently down and reconnecting; the test message went out, the tap will only arrive once it recovers",
        "daemon.warning.disconnected": "the ntfy subscription is down ({failures} consecutive failures, {seconds} s) and still reconnecting; replies arriving meanwhile will be replayed once it recovers",
        "daemon.warning.reconnected": "the ntfy subscription is back",
        "daemon.warning.text_during_confirm": "got a text reply, but only tapping the button counts as confirmation; tap “{button}” in the notification shade",
        "daemon.stopping.ask": "the daemon is stopping; the question went out, the user's later reply will be delivered as an instruction",
        "daemon.stopping.confirm": "the daemon is stopping; confirmation not completed — run confirm-sub again after restart",
        "daemon.confirm.busy_pending": "slot {slot} has a question waiting for a reply; confirm after it finishes",
        "daemon.confirm.busy_confirming": "slot {slot} is already being confirmed; wait for that to finish",
        "daemon.confirm.mark_failed": "button received, but saving the subscription state failed (see the daemon log); fix it and run confirm-sub again",
        "cli.start_hint": ("The daemon is not running. Start it:\n"
                           "  inside herdr : open another pane and run  agent-ntfy daemon      (visible, herdr owns its lifetime)\n"
                           "  outside herdr: agent-ntfy daemon --detach                     (detached; manage with --status / --stop)\n"
                           "  ⚠️ don't start it from the agent's own shell or as its background task — it dies with the agent"),
        "cli.connect_failed": "can't connect to the daemon ({path}: {error})",
        "cli.connect_failed.not_sent": "can't connect to the daemon ({path}: {error}). Message NOT sent.",
        "cli.no_response": "no response from the daemon",
        "cli.protocol.not_object": "the daemon replied with something that is not a JSON object",
        "cli.bad_env_lang": "AGENT_NTFY_LANG={value} is not a valid choice (only zh / en); set one of them or unset it (default en)",
        "cli.bad_env_ipc": "AGENT_NTFY_IPC={value} is not a valid choice (only unix / tcp); set one of them or unset it (platform default)",
        "help.prog": "Push decisions that need a human to your phone via ntfy.sh, and bring the verdict back",
        "help.home": "state directory (default {home})",
        "help.ask": "block and ask: reads the question JSON from stdin",
        "help.ask.timeout": "seconds to wait for a reply (default 12 hours)",
        "help.notify": "one-way notification (no buttons, no waiting); reads {\"title\", \"body\"} JSON from stdin",
        "help.daemon": "the resident subscriber process",
        "help.daemon.detach": "detach from the session and run in the background",
        "help.daemon.status": "show daemon status",
        "help.daemon.stop": "stop the daemon",
        "help.slots": "show the slot pool and leases",
        "help.release": "release a lease",
        "help.release.slot": "slot to release; omit to release the one leased by the current target",
        "help.confirm": "reachability check: verify the phone gets notifications for this slot (shows the topic name when run in a terminal; when an agent runs it inside herdr it opens a pane for the user)",
        "help.confirm.slot": "slot to confirm",
        "help.confirm.again": "re-confirm an already confirmed slot (after changing phones)",
        "help.confirm.subscribed": "user already subscribed: skip showing the topic and send the test notification right away (works outside a terminal)",
        "help.confirm.show_topic": "only print the topic name and exit, send nothing (it will land in the caller's output)",
        "help.confirm.timeout": "seconds to wait for the button tap (default 600)",
        "help.add_slot": "add a slot",
        "help.away": "remote-mode switch: on is one-stop (starts the daemon, makes sure a usable slot exists, then writes .agent-ntfy/state.json at the project root for the agent to read; no topic name in it)",
        "help.away.action": "on / off / status",
        "help.away.json": "with status: print state.json verbatim (for the agent)",
        # ---- away: per-project state file
        "cli.away.state.on": "remote mode: on",
        "cli.away.state.off": "remote mode: off",
        "cli.away.path": "state file: {path}",
        "cli.away.slot": "slot: {slot} ({gate})",
        "cli.away.slot.none": "slot: none leased yet (the first ask leases one)",
        "cli.away.target": "target: {target}",
        "cli.away.updated": "updated {updated}",
        "cli.away.not_enabled": "remote mode is not enabled for this project (no .agent-ntfy/ at the project root); to enable: agent-ntfy away on",
        "cli.away.io_failed": "could not read or write the state file: {error}",
        "cli.away.unverified": "daemon not running; not verified (the above is what the state file says)",
        "cli.away.corrected": "state file corrected from the daemon's leases",
        "cli.away.unverified.error": "the daemon could not report its leases; not verified (the above is what the state file says)",
        "cli.away.ready": "remote mode is on; slot {slot} is ready",
        "cli.away.ready.lazy": "remote mode is on; a slot is leased automatically on the first ask (the pool has a confirmed idle slot)",
        "cli.away.confirm_pane": ("remote mode is on, but slot {slot} still needs its reachability check: started it in herdr pane {pane}. Tell the user:\n"
                                  "  1. look at pane {pane} and subscribe to the topic it shows in the ntfy app\n"
                                  "  2. once subscribed, press Enter in that pane — a test notification with a button arrives\n"
                                  "  3. tap the button in the notification shade; then check agent-ntfy slots to see whether it is confirmed"),
        "cli.away.confirming": ("remote mode is on; slot {slot} is being confirmed right now (a confirmation pane is already open):\n"
                                "  have the user finish subscribing and press Enter in that pane, then tap the button on the phone"),
        "cli.away.daemon_failed": "the daemon did not come up (not reachable within {seconds} s); remote mode NOT enabled. See the log {log}",
        "cli.away.unwritable": "state directory {path} is not writable (exists but is not a directory, or no write permission)",
        "cli.away.pane_failed": "could not open a herdr pane (or the command did not get typed in); the daemon was not started and remote mode is NOT enabled. Run agent-ntfy daemon --detach in a terminal, then retry",
        "cli.slots.pane": "  pane {pane}",
        "cli.project.unresolved": "cannot tell which project this is ({error}); run from a directory that exists",
        "cli.reminder": "note: {message}",
        "cli.notify.sent": "notification sent on {slot} (if the user replies, it arrives as an instruction)",
        "cli.ask.timeout": "no reply within {seconds} s (the message was sent; the user's later reply will be delivered as an instruction)",
        "cli.ask.error_sent": "message sent, but {message}",
        "cli.ask.error_not_sent": "message NOT sent: {message}",
        "cli.ask.candidate": "  candidate: {slot} ({gate})",
        "cli.ask.candidate.confirmed": "confirmed",
        "cli.ask.candidate.unconfirmed": "unconfirmed — picking it means one more round on the phone",
        "cli.ask.disconnected": "connection to the daemon lost",
        "cli.ask.disconnected.sent": " (message sent; the reply can no longer reach this call)",
        "cli.ask.disconnected.not_sent": " (message NOT sent)",
        "cli.ask.comm_failed": "talking to the daemon failed: {error}",
        "cli.ask.comm_failed.sent": " (message sent)",
        "cli.ask.interrupted": "interrupted",
        "cli.ask.interrupted.sent": " (message sent; the user's later reply will be delivered as an instruction)",
        "cli.slots.gate.confirmed": "confirmed",
        "cli.slots.gate.unconfirmed": "unconfirmed",
        "cli.slots.since": "  {leased_by}  since {leased_at}",
        "cli.slots.state.unassigned": "unassigned",
        "cli.slots.state.idle": "leased, idle",
        "cli.slots.state.active": "leased, active",
        "cli.slots.state.confirming": "confirming",
        "cli.released": "released {slot}",
        "cli.confirm.topic": "topic for {slot}: {topic}\nsubscribe URL: {url}",
        "cli.confirm.topic_hint": ("The topic name is only shown in your own terminal: run  agent-ntfy confirm-sub {slot}  there yourself.\n"
                                   "  If the user already subscribed on the phone, add --subscribed (no topic shown, works outside a terminal); to only print the topic use --show-topic (it will land in the caller's output)"),
        "cli.confirm.guide": "Subscribe to the topic above in the ntfy app on your phone. Once subscribed, press Enter and I'll send a test notification with a button — when it pops up, tap the button and the check is done.",
        "cli.confirm.enter": "Press Enter once subscribed…",
        "cli.confirm.already": "{slot} is already confirmed to reach the phone; nothing to do. Changed phones? Add --again to confirm anew",
        "cli.confirm.protocol": "protocol error: got a topic event despite --subscribed; not printing it. daemon and CLI versions may differ",
        "cli.confirm.no_enter": "no Enter received (stdin ended); confirmation cancelled. Run it interactively in your own terminal, or use --subscribed if the user already subscribed",
        "cli.confirm.sent": "test notification sent — tap “{button}” in the phone's notification shade (within {seconds} s)…",
        "cli.confirm.done": "✅ {slot} confirmed: the phone gets notifications; the agent can use it for questions from now on",
        "cli.confirm.timeout": "no button tap within {seconds} s; confirmation not completed. Nothing popped up? Go through the README troubleshooting list and run it again",
        "cli.confirm.timeout_no_enter": "no Enter within {seconds} s; confirmation not completed and the test notification was never sent. Subscribe first, then run it again",
        "cli.confirm.disconnected": "connection to the daemon lost; confirmation not completed",
        "cli.confirm.comm_failed": "talking to the daemon failed: {error}",
        "cli.confirm.interrupted": "interrupted; confirmation not completed",
        "cli.confirm.pane_opened": ("Started the reachability check for {slot} in herdr pane {pane}. Tell the user:\n"
                                    "  1. look at pane {pane} and subscribe to the topic it shows in the ntfy app\n"
                                    "  2. once subscribed, press Enter in that pane — a test notification with a button arrives\n"
                                    "  3. tap the button in the notification shade; then check agent-ntfy slots or away status to see whether it is confirmed"),
        "cli.add_slot.done": "added {slot} (not yet confirmed to reach the phone). Next: run  agent-ntfy confirm-sub {slot}  in your own terminal",
        "cli.status.not_running": "daemon: not running",
        "cli.status.no_socket": "daemon: no answer (pid file {pid} still there; it may have died)",
        "cli.status.transport": "  transport: {transport}",
        "cli.status.sub.connected": "connected",
        "cli.status.sub.connecting": "connecting",
        "cli.status.sub.disconnected": "down for {seconds} s",
        "cli.status.line": "daemon: pid {pid}  subscription: {sub}  pending questions: {pending}  confirming: {confirming}  slots: {pool}",
        "cli.stop.no_ack": "daemon (pid {pid}) did not acknowledge the stop ({other}); please check by hand",
        "cli.stop.no_response": "no response",
        "cli.stop.done": "daemon: pid {pid} stopped",
        "cli.stop.timeout": "daemon pid {pid} did not exit within 30 s",
        "cli.detach.already": "a daemon is already running",
        "cli.detach.died": "the daemon did not come up (exit code {rc}), see {log}",
        "cli.detach.started": "daemon: started in the background, pid {pid} (log {log})",
        "cli.detach.not_ready": "daemon (pid {pid}) not ready within 5 s, still starting; check later with agent-ntfy daemon --status, log {log}",
        "validate.header": "agent-ntfy ask: input validation failed ({n} issue(s)); fix them all and retry. Message NOT sent.",
        "validate.field.body": "body",
        "validate.hint.title": "the one-line hook shown in the notification shade — the preview shows nothing else",
        "validate.hint.doing": "one sentence: which task this is",
        "validate.hint.description": "the background, written for someone who has not seen any of the work",
        "validate.hint.blocker": "exactly what is blocked",
        "validate.hint.options": "2-5 items of {id, label, consequence}; consequence states the real outcome",
        "validate.hint.recommend": "the id of the recommended option",
        "validate.hint.reasoning": "why you lean that way + the strongest objection",
        "validate.hint.question": "one question answerable in one sentence",
        "validate.missing": "missing",
        "validate.not_array": "not an array (it is {type})",
        "validate.empty_array": "an empty array",
        "validate.not_string": "not a string (it is {type})",
        "validate.empty_string": "an empty string",
        "validate.required": "{why}. Required: {hint}",
        "validate.options.too_few": "only {n} item(s); {min}-{max} required (a single option is not a choice)",
        "validate.options.too_many": "{n} items; {min}-{max} required (more than {max} means the question hasn't converged — think it through first)",
        "validate.options.not_object": "item {i} is not an object (it is {type}). Each item needs id / label / consequence",
        "validate.options.lacking": "item {i} lacks {keys}. Each item needs id / label / consequence, all non-empty",
        "validate.options.dup_id": "duplicate id: {id} (items {where})",
        "validate.options.dup_sep": ", ",
        "validate.recommend": '"{rec}" is not one of the option ids (existing ids: {ids})',
        "validate.recommend.none": "none",
        "validate.lang": '"{value}" is not a valid choice (only {choices}); it selects the language of the fixed wording — omit it to fall back to AGENT_NTFY_LANG, then en',
        "validate.body_too_long": "renders to {size} bytes, limit {limit}, {over} bytes over. Trim description / consequence / reasoning (nothing is truncated for you)",
        "validate.title_too_long": "{size} bytes, limit {limit}, {over} bytes over. title is the one-line hook in the notification shade — keep it short",
        "validate.title_newline": "contains a line break. title is a single notification line",
        "validate.top_not_object": "the top level must be an object, got {type}",
        "validate.bad_json": "not valid JSON: {msg} (line {line}, column {col})",
        "state.none": "none",
        "state.all_leased": "all slots are leased; idle slots that could be taken over: {candidates}",
        "state.keychain.bad_name": "keychain {label} is invalid: {value} (letters, digits, . _ - only)",
        "state.keychain.label.service": "service name",
        "state.keychain.label.account": "account name",
        "state.keychain.read_failed": "reading keychain item '{service}' failed (rc={rc}): {detail}",
        "state.keychain.write_failed": "writing keychain item '{service}' failed (rc={rc}): {detail}",
        "state.keychain.not_json": "keychain item '{service}' does not hold a JSON array: {error}",
        "state.keychain.not_str_array": "keychain item '{service}' does not hold an array of strings",
        "state.keychain.readback_mismatch": "keychain item '{service}' read back differently from what was written; the pool was not updated",
        "state.file.corrupt": "topic pool file {path} is not a JSON array of strings ({error}); if it was not edited by hand, move it away and restart (a new pool is generated; the phone must re-subscribe)",
        "state.file.read_failed": "reading topic pool file {path} failed: {error}",
        "state.file.write_failed": "writing topic pool file {path} failed: {error}",
        "state.keychain.missing": "the security command was not found (the keychain exists only on macOS); on other platforms set AGENT_NTFY_STORE=file (Linux) or dpapi (Windows)",
        "state.store.bad_env": "AGENT_NTFY_STORE={value} is not a valid choice (only {choices}); leave it unset for the platform default: macOS keychain / Windows DPAPI / 0600 file elsewhere",
        "state.dpapi.unavailable": "DPAPI is only available on Windows (this platform is {platform}); elsewhere use AGENT_NTFY_STORE=file or keychain",
        "state.dpapi.unprotect_failed": "decrypting topic pool file {path} failed ({error}): only the Windows user who encrypted it can decrypt it, and only on the same machine; after changing account / machine move it away and restart (a new pool is generated; the phone must re-subscribe)",
        "state.slot.bad_name": "invalid slot name: {slot} (expected something like slot1)",
        "state.slot.missing": "slot {slot} does not exist (the pool only has {n})",
        "state.active.not_leased": "active slot {slot} is not leased in the lease file; state is inconsistent, refusing",
        "state.prefix.bad": "invalid topic prefix: {prefix} (letters, digits, - and _ only, at most 40)",
        "state.pool.too_small": "the pool needs at least 1 slot, got {pool_size}",
        "state.leases.read_failed": "reading the lease file {path} failed: {error}",
        "state.leases.not_object": "the lease file {path} is not a JSON object",
        "state.leases.write_failed": "writing the lease file {path} failed: {error}",
        "state.replace.active": "slot {slot} has a question waiting for a reply; can't replace it",
        "state.replace.unassigned": "slot {slot} has no lease; just acquire it, no replacement needed",
        "state.replace.unconfirmed": "slot {slot} is unconfirmed; while the user is away only confirmed slots can be used",
        "state.touch.unassigned": "slot {slot} has no lease; no pane to refresh",
        "state.grant.empty_owner": "leased_by must not be empty (say who is using the slot)",
        "state.release.active": "slot {slot} has a question waiting for a reply; can't release it",
        "state.release.unassigned": "slot {slot} has no lease; nothing to release",
        "ntfy.action.empty": "a button needs both a label and a url",
        "ntfy.name.not_string": "{kind} is not a string (got {type})",
        "ntfy.name.invalid": "{kind} is invalid: {why} (length {n}). Letters, digits, - and _ only, 1-64 characters",
        "ntfy.name.kind.topic": "topic",
        "ntfy.name.kind.seq": "sequence ID",
        "ntfy.name.why.empty": "empty",
        "ntfy.name.why.too_long": "too long",
        "ntfy.name.why.whitespace": "contains whitespace",
        "ntfy.name.why.illegal": "contains illegal characters",
        "ntfy.message.empty": "the message body must not be empty",
        "ntfy.message.too_long": "the body is {n} bytes, over {limit}; ntfy would turn it into an attachment instead of a message",
        "ntfy.actions.too_many": "{n} buttons; ntfy allows at most {limit}",
        "ntfy.action.not_object": "a button is not an object (got {type})",
        "ntfy.action.malformed": "malformed button: it needs at least action and label; fields present: {fields}",
        "ntfy.title.newline": "the title must not contain a line break",
        "ntfy.echo.topic": "the server recorded a different topic from the one sent: {brief}",
        "ntfy.echo.title": "the title echoed back differs: sent {sent}, server recorded {got}",
        "ntfy.echo.actions": "the server echoed {got} button(s), {sent} were sent — the JSON was not parsed as JSON (published to the wrong endpoint?): {brief}",
        "ntfy.echo.attachment": "the server turned the body into an attachment instead of a message (body too long?): {brief}",
        "ntfy.closed": "the subscription was closed by this process",
        "ntfy.stream.broken": "the subscription stream broke: {error}",
        "ntfy.stream.eof": "the subscription stream was closed by the server (no timeout, no error); reconnect needed",
        "ntfy.stream.not_utf8": "a line in the subscription stream is not UTF-8 ({n} bytes)",
        "ntfy.stream.not_json": "a line in the subscription stream is not JSON ({n} bytes)",
        "ntfy.stream.not_object": "a line in the subscription stream is not a JSON object ({n} bytes)",
        "ntfy.update.seq_mismatch": "the server returned a sequence_id other than {seq}; this update did not attach to the original message: {brief}",
        "ntfy.clear.no_event": "the server did not return a message_clear event: {brief}",
        "ntfy.clear.seq_mismatch": "the clear event attached to another sequence, not {seq}: {brief}",
        "ntfy.subscribe.empty": "subscribe to at least one topic",
        "ntfy.connect.no_socket": "no socket available after connecting",
        "ntfy.connect.failed": "can't reach {url}: {error}",
        "ntfy.response.not_json": "the server did not return JSON: {payload}",
        "ntfy.response.not_object": "the server did not return a JSON object: {payload}",
        "ntfy.http": "HTTP {status} {reason}",
        "ntfy.http.detail": "HTTP {status} {reason}: {detail}",
        "ntfy.http.ntfy_code": "{error} (ntfy code {code})",
        "ntfy.http.rate_limited": "{msg}. This is rate limiting, not a code error",
        "daemon_error.bad_lang": "lang must be one of zh / en, got {value}",
        "daemon_error.socket": "cannot listen for IPC: {path}: {error}{hint}",
        "daemon_error.socket.unix_hint": ". Unix socket paths have a length limit (system-dependent); pick a shorter AGENT_NTFY_HOME",
        "daemon_error.unauthorized": "unauthenticated connection (token mismatch)",
        "daemon_error.bad_ipc": "AGENT_NTFY_IPC must be unix or tcp: {error}",
        "daemon_error.state_init": "state initialisation failed: {error}",
        "daemon_error.already_running": "a daemon is already running ({path} accepts connections); not starting a second one",
        "help.timeout.not_number": "not a number: {text}",
        "help.timeout.not_positive": "must be greater than 0 seconds: {text}",
    },
}


class Ref:
    """嵌在占位参数里的另一条文案：t() 取值时按同一语言解析。异常对象（StateError / NtfyError / DaemonError）带 text(lang) 的也同样处理。"""

    def __init__(self, key: str, **fmt):
        self.key, self.fmt = key, fmt


def is_lang(value: object) -> bool:
    return isinstance(value, str) and value in LANGS


def resolve(explicit: object, env: object) -> str:
    """显式值（ask JSON 的 lang）> 环境变量值 > en。非法值当没给：显式值的非法由校验层另外报错，不在这里处理。"""
    if is_lang(explicit):
        return str(explicit)
    if is_lang(env):
        return str(env)
    return DEFAULT_LANG


def t(key: str, lang: str, **fmt) -> str:
    """取一条固定文案。lang 不是 zh / en 或 key 不存在都抛 KeyError——那是调用方的 bug，不能静默回退成别的语言。

    占位参数里的 Ref 与带 text(lang) 的对象按同一语言解析后再填进去。
    """
    if lang not in TEXTS:
        raise KeyError(f"unsupported lang {lang!r}")
    text = TEXTS[lang][key]
    if not fmt:
        return text
    resolved = {k: (t(v.key, lang, **v.fmt) if isinstance(v, Ref) else v.text(lang) if callable(getattr(v, "text", None)) else v)
                for k, v in fmt.items()}
    return text.format(**resolved)
